# Generated by Django 5.2.9 on 2025-12-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
