# Generated by Django 5.2.9 on 2025-12-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_uploadedpdf_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
