# Generated by Django 5.2.9 on 2025-12-21 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0003_uploadedpdf_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='pdf_pages/')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='rag_app.uploadedpdf')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
